#include<iostream>
using namespace std;
int main()
{
    int n;
    cout<<"the size of int "<<sizeof(n)<<endl;
    float f;
    cout << "the size of float " << sizeof(f) << endl;
    double d;
    cout << "the size of double " << sizeof(d) << endl;
    char ch;
    cout << "the size of char " << sizeof(ch) << endl;
    bool bl;
    cout << "the size of bool " << sizeof(bl) << endl;

    return 0;
}